config/routes.rb
get :responsibility_list, to: 'list#index'
get :membership_list,     to: 'list#membership_list'

app/models/membership_history.rb
class MembershipHistory < ActiveRecord::Base
  unloadable

  attr_accessible :role_id, :user_id, :project_id, :given

  belongs_to :user
  belongs_to :project
end

app/controllers/list_controller.rb
require 'list_handler'

class ListController < ApplicationController
  unloadable

  skip_before_filter :session_expiration, :user_setup, :check_if_login_required, :set_localization, if: :api_request?
  before_filter :permitted_or_api_request?

  def index
    @list_handler = ListHandler.new
    @full_list = @list_handler.generate
    respond_to do |format|
      format.html
      format.json { render :json => @full_list.to_json }
    end
  end

  def membership_list
    search_params = {}
    %w(project_id user_id role_id).each do |param|
      search_params[param] = params[param] unless params[param].blank? || params[param] == 'all'
    end
    unless params[:given].blank? || params[:given] == 'all'
      search_params[:given] = (params[:given] == '1') ? true : (params[:given] == '0' ? false : nil)
    end
    @memberships = MembershipHistory.where(search_params)

    @paginate, @memberships = paginate @memberships.order('created_at DESC'), :per_page => 20
  end

  private

  def permitted_or_api_request?
    deny_access unless api_request? && proper_auth_key? || User.current.admin? || has_access?
  end

  def proper_auth_key?
    # http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.8
    request.headers['Authorization'] == Setting.plugin_redmine_responsibility_list[:auth_key]
  end

  def has_access?
    !(user_ids & groups_with_access).blank?
  end

  def user_ids
    User.current.groups.select('id').collect{|el| el.id.to_s}
  end

  def groups_with_access
    Setting.plugin_redmine_responsibility_list[:groups] || []
  end
end

app/helpers/list_helper.rb
module ListHelper

  def multiple_user_link(user_logins)
    return nil if user_logins.empty?
    users = User.select([:id, :login, :firstname, :lastname]).where(login: user_logins)
    users.map{|user| link_to("#{user.to_s} (#{user.login})", user_path(user))}.join(', ').html_safe
  end

  def render_membership_icon(membership)
    if membership.given
      "<img src='/images/toggle_check.png' title='role given' alt='role given'>".html_safe
    else
      "<img src='/images/locked.png' title='role taken away' alt='role taken away'>".html_safe
    end
  end

  def select_with_caption(name, caption, option_tags = nil, opts = {})
    select_opts = "<option value=''>#{caption}</option><option value='all'>All</option>".html_safe + option_tags
    select_tag(name, select_opts, opts)
  end

  def render_link_to_memberships(project_data)
    id = Project.select(:id).where(name: project_data[:name]).first.id
    link_to 'history', membership_list_path(project_id: id), class: "icon icon-user", style: "line-height:1.4em;font-size:0.9em;"
  end
end

app/views/list/_resp_navbar.html.erb
<div class="tabs">
  <ul>
    <li><a href="<%= responsibility_list_path %>" class="<%= action_name == 'index' ? 'selected' : nil %>" id="tab-list">Responsibility list</a></li>
    <li><a href="<%= membership_list_path %>" class="<%= action_name == 'membership_list' ? 'selected' : nil %>" id="tab-memberships">Memberships</a></li>
  </ul>
</div>

app/views/list/_table_body.html.erb
<tbody>
  <% if !list.empty? %>
    <% list.each do |project| %>
      <tr>
        <td style="width:8%"><%= link_to project[:name], Project.find_by_name(project[:name]) %></td>
        <td style="width:8%"><%= project[:code_name] %></td>
        <td style="width:8%"><%= project[:page] %></td>
        <td style="width:10%"><%= multiple_user_link(project[@list_handler.roles[0]]) %></td>
        <td style="width:10%"><%= multiple_user_link(project[@list_handler.roles[1]]) %></td>
        <td style="width:10%"><%= multiple_user_link(project[@list_handler.roles[2]]) %></td>
        <td style="width:10%"><%= multiple_user_link(project[@list_handler.roles[3]]) %></td>
        <td style="width:10%"><%= multiple_user_link(project[@list_handler.roles[4]]) %></td>
        <% custom_fields.each do |custom_field| %>
          <td style="text-align:center;width:5%">
            <% if custom_field.field_format == 'bool' %>
              <input type="checkbox" disabled=true <%= project[custom_field.name] == true ? "checked" : nil %> />
            <% elsif custom_field.field_format == 'user' %>
              <%= User.find_by_id(project[custom_field.name]) ? link_to_user(User.find(project[custom_field.name])) : nil %>
            <% else %>
              <%= project[custom_field.name] %>
            <% end %>
          </td>
        <% end %>
        <td style="text-align:center;width:5%"><%= render_link_to_memberships(project) %></td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/list/_table_header.html.erb
<thead>
  <tr>
    <th><%= t(:project) %></th>
    <th><%= t(:code_name) %></th>
    <th><%= t(:url) %></th>
    <th><%= Setting.plugin_redmine_responsibility_list[:roles][:role1][:title] %></th>
    <th><%= Setting.plugin_redmine_responsibility_list[:roles][:role2][:title] %></th>
    <th><%= Setting.plugin_redmine_responsibility_list[:roles][:role3][:title] %></th>
    <th><%= Setting.plugin_redmine_responsibility_list[:roles][:role4][:title] %></th>
    <th><%= Setting.plugin_redmine_responsibility_list[:roles][:role5][:title] %></th>
    <% if @list_handler.custom_fields %>
      <% @list_handler.custom_fields.each do |custom_field| %>
        <th><%= custom_field.name %></th>
      <% end %>
    <% end %>
    <th></th>
  </tr>
</thead>

app/views/list/index.html.erb
<%= render :partial => 'resp_navbar' %>

<h1 style="padding-bottom:15px;"><%= t(:responsibility_list) %></h1>
<h2><%= t(:open_projects) %></h2>
<table class="list">
  <%= render 'table_header' %>
  <%= render 'table_body', :list => @full_list[:open], :custom_fields => @list_handler.custom_fields %>
</table>
<br />
<h2><%= t(:closed_projects) %></h2>
<table class="list">
  <%= render 'table_header' %>
  <%= render 'table_body', :list => @full_list[:closed], :custom_fields => @list_handler.custom_fields %>
</table>
<br />
<h2><%= t(:archived_projects) %></h2>
<table class="list">
  <%= render 'table_header' %>
  <%= render 'table_body', :list => @full_list[:archived], :custom_fields => @list_handler.custom_fields %>
</table>

app/views/list/membership_list.html.erb
<%= render :partial => 'resp_navbar' %>

<h1><%= t('membership.memberships') %></h1>

<div class="splitcontentleft" style="width:70%;">
  <table class="list" style="margin-top:10px;">
    <thead>
      <tr>
        <th><%= t('project') %></th>
        <th><%= t('user') %></th>
        <th><%= t('role') %></th>
        <th><%= t('membership.type') %></th>
        <th><%= t('membership.date') %></th>
      </tr>
    </thead>
    <tbody>
        <% @memberships.each do |membership| %>
          <tr style="height:25px;">
            <td style="width:27%"><%= link_to membership.project, project_path(membership.project) %></td>
            <td style="width:23%"><%= multiple_user_link(membership.user.login) %></td>
            <td style="width:20%"><%= Role.find(membership.role_id).name %></td>
            <td style="width:7%"><%= render_membership_icon(membership) %></td>
            <td style="width:23%"><%= membership.created_at.to_s(:db) %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
  <p class="pagination" style="padding-top:12px;"><%= pagination_links_full @paginate %></p>
</div>

<div class="splitcontentright" style="width:29%;">
  <%= form_tag membership_list_path, method: :get do %>
    <fieldset>
      <legend><%= t('filter.filters') %></legend>
      <%= select_with_caption :project_id, t('filter.project'), options_from_collection_for_select(Project.all, "id", "name", selected: params[:project_id]), class: "form-control", id: 'filter-project',:onchange => "this.form.submit(); return false;" %>

      <%= select_with_caption :user_id, t('filter.user'), options_from_collection_for_select(User.where("lastname != :name", :name => 'Anonymous'), "id", "fullname_with_login", selected: params[:user_id]), class: "form-control", id: 'filter-user', :onchange => "this.form.submit(); return false;" %>

      <%= select_with_caption :role_id, t('filter.role'), options_from_collection_for_select(Role.where("name != :name", :name => 'Anonymous'), "id", "name", selected: params[:role_id]), class: "form-control", id: 'filter-role', :onchange => "this.form.submit(); return false;" %>

      <%= select_with_caption :given, t('filter.type'), options_for_select([["Given", '1'], ["Taken away", '0']], selected: params[:given]), class: "form-control", id: 'filter-given', :onchange => "this.form.submit(); return false;" %>
      <div class="contextual">
        <%= link_to t('filter.reset'), membership_list_path, class: "icon icon-reload" %>
      </div>
    </fieldset>
  <% end %>
</div>
<%= javascript_tag do %>
  $('#filter-project').selectize();
  $('#filter-user').selectize();
  $('#filter-role').selectize();
  $('#filter-given').selectize();
<% end %>
<% content_for :header_tags do %>
  <%= javascript_include_tag 'selectize.min.js',   :plugin => 'redmine_responsibility_list' %>
  <%= stylesheet_link_tag 'selectize.default.css', :plugin => 'redmine_responsibility_list' %>
<% end %>

app/views/settings/_responsibility_settings.html.erb
<div id="info">
  <h3><%= t(:please_provide) %></h3>
  <ul>
    <li><%= t(:provide_titles) %></li>
    <li><%= t(:provide_roles) %></li>
  </ul>
</div>
<div id="list">
  <table style="width: 100%">
    <thead>
      <th><%= t(:role_title) %></th>
      <th><%= t(:roles) %></th>
    </thead>
    <tbody>
      <% Setting.plugin_redmine_responsibility_list[:roles].each_with_index do |(k,v),i| %>
        <tr>
          <td style="width: 20%">
            <%= text_field_tag "settings[[roles][role#{i+1}][title]]", v[:title], :autocomplete => 'off', class: "basictxt", id: "title#{i+1}" %>
          </td>
          <td style="width: 80%">
            <%= select_tag "settings[[roles][role#{i+1}][names]]",
               options_for_select(
                 Role.pluck(:name),
                 Setting.plugin_redmine_responsibility_list[:roles]["role#{i+1}".to_sym][:names]
                 ), :multiple => true, :id => "names#{i+1}" %>
          </td>
        </tr>
      <% end %>
  </table>
  <h4><%= t(:custom_header) %></h4>
  <div style="width:100%;">
    <%= select_tag "settings[custom_fields]",
      options_from_collection_for_select(CustomField.where(type: "ProjectCustomField"), 'id', 'name',
        Setting.plugin_redmine_responsibility_list[:custom_fields]
        ), :multiple => true, :id => "custom_fields" %>
  </div>
  <h4><%= t(:allowed_groups) %></h4>
  <div style="width:100%;">
      <%= select_tag "settings[groups][]",
        options_from_collection_for_select(Group.all, 'id', 'lastname',
          Setting.plugin_redmine_responsibility_list[:groups]
          ), :multiple => true, :id => "groups" %>
  </div>
  <div class="form-elem">
    <h4><%= t(:auth_header) %></h4>
    <div style="height:25px;">
      <div class="splitcontentleft" style="width:20%;">
        <%= text_field_tag "settings[[auth_key]]", Setting.plugin_redmine_responsibility_list[:auth_key], class: "basictxt", id: "auth_key", :autocomplete => 'off' %>
      </div>
      <div class="splitcontentright" style="width:80%;">
        <div class="auth-example">
          <p><u><i>Usage with curl:</i></u><br />curl --header "Authorization: </p><p id="auth_val_hidden"><%= Setting.plugin_redmine_responsibility_list[:auth_key] %></p><p><%= "\" #{responsibility_list_url}.json" %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'selectize.min.js',   :plugin => 'redmine_responsibility_list' %>
  <%= javascript_include_tag 'settings_page.js',   :plugin => 'redmine_responsibility_list' %>
  <%= stylesheet_link_tag 'selectize.default.css', :plugin => 'redmine_responsibility_list' %>
  <%= stylesheet_link_tag 'custom_styles.css',     :plugin => 'redmine_responsibility_list' %>
<% end %>